### ISSUE TITLE
pubsub: non-retryable rpc errors in subscription `Receive()` method

### ISSUE THREAD

**Issue by maximerety** [googleapis/google-cloud-go#4257]
**Client**

PubSub

**Environment**

Ubuntu Focal on GKE

**Go Environment**

$ go version
go version go1.16.5

**Code**

We're using the standard way to receive messages from a subscription, with default configurations (similar to the [code snippet from doc](https://pkg.go.dev/cloud.google.com/go/pubsub#hdr-Receiving)):

```go
 err := subscription.Receive(context.Background(), func(ctx context.Context, m *Message) {
 	log.Printf("Got message: %s", m.Data)
 	m.Ack()
 })
 if err != nil {
	// Handle error.
 }
```

We've managed to use this method for several months in long-living containers, without receiving any (non-retryable) errors.

On June 2, 2021, we started to receive sporadic fatal RPC errors in the following forms:

```
rpc error: code = Unknown desc = closing transport due to: connection error:
  desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data: server_shutting_down

rpc error: code = Unknown desc = closing transport due to: connection error:
  desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data: max_age

rpc error: code = Unknown desc = closing transport due to: connection error:
  desc = "error reading from server: read tcp <ip>:54780-><ip>:443: read: connection reset by peer", received prior goaway: code: NO_ERROR, debug data: max_age
```

We've seen these kinds of errors several times per day since then.

**Expected behavior**

Automatic internal retries on these kinds of RPC errors, so that the [Receive()](https://pkg.go.dev/cloud.google.com/go/pubsub#Subscription.Receive) method doesn't error.

I've noticed that there is a piece of retrying logic in [pubsub/service.go](https://github.com/googleapis/google-cloud-go/blob/pubsub/v1.11.0/pubsub/service.go#L51) that detects server shutdowns associated to the `Unavailable` code and the `"Server shutdownNow invoked"` message.

Maybe something recently changed in the way the remote server signals that it is shutting down and this logic needs to be updated?

**Actual behavior**

The [Receive()](https://pkg.go.dev/cloud.google.com/go/pubsub#Subscription.Receive) method from the subscription errors.

**Additional context**

Started on June 2, 2021.

Not long after we upgraded to pubsub [v1.11.0](https://github.com/googleapis/google-cloud-go/releases/tag/pubsub%2Fv1.11.0), although I don't see how it would be related - so I'm mentioning this mostly for completeness.

**Comment by hongalex** [comment]
Thanks for reporting. This error is actually being returned by a reverse proxy server rather than the Pub/Sub service itself, and the issue you described affects all of our Pub/Sub libraries. Assuming you're not overriding connections, this is likely just an issue with the server getting hitting a large number of connections. I'll submit a fix for this later this week to get this retried automatically.

**Comment by maximerety** [comment]
Hi @hongalex, thank you for this quick update. If I can be of any help, don't hesitate to ask.

**Comment by noseglid** [comment]
Any news here? This is hitting us hard recently.

**Comment by noseglid** [comment]
I did some investigation since this seems to not happen for some services we have running, while it happens continually for others. After som digging I managed to boil it down to one dependency; `google.golang.org/grpc`.

I have 2 github tags in my service, and when I do `go list -m all` for each tag, the only dependency that differs is `google.golang.org/grpc`.

One tag is using` google.golang.org/grpc v1.37.0` and this **has no issues**.
The other tag is using `google.golang.org/grpc v1.38.0` and this **shows the issue described in this ticket**.

Maybe it's an issue with a proxy, but it definitely seems to depend on some behaviour of the grpc lib as well.

**Comment by hongalex** [comment]
Apologies for the delay, other issues had crept up. I have a PR open to get this addressed in the short term, and will be following up on another PR to allow custom retries of our methods so workarounds will be available earlier. This fix should be merged/released later today.

**Comment by noseglid** [comment]
Is there any ETA on when this will be released? Seems like it didn't make it into the previous (v1.12) release.

**Comment by hongalex** [comment]
This should be released in in v1.12.1 via #4334 shortly. Thanks for your patience

**Comment by noseglid** [comment]
Unfortunately this still happens. Much less frequent but still. Now with this error:
```
rpc error: code = Unknown desc = closing transport due to: connection error: desc = \"error reading from server: read tcp 10.0.234.233:37960->74.125.133.95:443: read: connection reset by peer\", received prior goaway: code: NO_ERROR, debug data: server_shutting_down
```

[The fix](https://github.com/googleapis/google-cloud-go/pull/4313) doesn't work because it says `error reading from server: read tcp` not `error reading from server: EOF` which the fix expects.

Should it perhaps retry on an gRPC error with status code unknown instead?

**Comment by hongalex** [comment]
Yeah, that was an oversight on my part. I don't think we want to retry _all_ unknown errors (based on [AIP](https://google.aip.dev/194)), but I'll fix the error message checking to just check for `received prior goaway: code: NO_ERROR` instead. I'll try to get this released later today.
